'use strict';
const assert=require('assert');
const mobile=require('../hero072/mobile-controls.js');
let passed=0;function test(name,fn){fn();passed++;console.log(`✓ ${name}`);}
test('keyboard controls stay hidden on touch-only devices unless advanced mode is explicit',()=>{assert(!mobile.controlsTabVisible({finePointer:false,keyboard:false}));assert(mobile.controlsTabVisible({finePointer:true,keyboard:false}));assert(mobile.controlsTabVisible({finePointer:false,keyboard:false},true));});
test('pinch state clamps zoom and consumes the two-pointer gesture',()=>{const p=mobile.createPinchState(1,.65,1.65);assert(!p.down(1,0,0));assert(p.down(2,100,0));assert.strictEqual(p.move(2,300,0).zoom,1.65);assert(p.up(1));assert(!p.pinching);});
test('pinch state resets its baseline when a replacement pointer joins',()=>{const p=mobile.createPinchState(1);p.down(1,0,0);p.down(2,100,0);p.move(2,150,0);p.up(1);p.down(3,50,0);assert.strictEqual(p.move(2,250,0).zoom,1.65);p.up(2);p.up(3);assert(!p.pinching);});
test('minimap remains within portrait and above mobile landscape controls',()=>{for(const [w,h,landscape,touch] of [[390,844,false,true],[430,932,false,true],[844,390,true,true],[1366,768,true,false]]){const m=mobile.minimapLayout(w,h,landscape,touch);assert(m.x-m.r>=0);assert(m.x+m.r<=w);assert(m.y-m.r>=0);assert(m.y+m.r<=h);if(touch)assert(m.y+m.r<=h-(landscape?132:286));}});
test('camera zoom stays centered, clamps at world edges and maps effects to screen pixels',()=>{const center=mobile.cameraViewport({x:500,y:400},390,844,1.5,2000),screen=mobile.worldToScreen({x:500,y:400},center,1.5);assert.strictEqual(center.x,370);assert(Math.abs(center.y-118.66666666666669)<1e-9);assert(Math.abs(screen.x-195)<1e-9);assert(Math.abs(screen.y-422)<1e-9);const edge=mobile.cameraViewport({x:5,y:5},390,844,9,2000);assert.strictEqual(edge.zoom,1.65);assert.strictEqual(edge.x,0);assert.strictEqual(edge.y,0);});
test('locked target persists through movement and dodge but cleans up on death, unload and range break',()=>{const hero={x:0,y:0},target={x:100,y:0},enemies=[target];assert.strictEqual(mobile.validTarget(target,enemies,hero),target);hero.x=20;assert.strictEqual(mobile.validTarget(target,enemies,hero),target);target.dead=true;assert.strictEqual(mobile.validTarget(target,enemies,hero),null);target.dead=false;assert.strictEqual(mobile.validTarget(target,[],hero),null);target.x=900;assert.strictEqual(mobile.validTarget(target,enemies,hero,720),null);});
test('unfair sanctuary damage causes retreat, disengagement and normal AI resumption',()=>{const camp={x:0,y:0},hero={x:0,y:0},wolf={x:280,y:0,unfairDamage:true};assert.strictEqual(mobile.retreatState(wolf,hero,camp,260,150).state,'sanctuary-retreat');wolf.x=420;assert.strictEqual(mobile.retreatState(wolf,hero,camp,260,150).state,'resume');assert.strictEqual(wolf.unfairDamage,false);assert.strictEqual(mobile.retreatState(wolf,hero,camp,260,150),null);});
test('leaving sanctuary cancels stale unfair-damage retreat',()=>{const wolf={x:280,y:0,unfairDamage:true};assert.strictEqual(mobile.retreatState(wolf,{x:400,y:0},{x:0,y:0},260,150).state,'resume');assert.strictEqual(wolf.unfairDamage,false);});
console.log(`\n${passed}/8 Stage 2A mobile follow-up tests passed.`);
