(function (root, factory) {
  const value = factory();
  if (typeof module === 'object' && module.exports) module.exports = value;
  else root.MonsterWorldV04Config = value;
})(typeof globalThis !== 'undefined' ? globalThis : self, function () {
  'use strict';

  const RINGS = [
    { id: 'edge', label: 'Окраина', min: 0, max: 89, outer: 1.00, inner: 0.82, energy: 0.08 },
    { id: 'low', label: 'Низкое кольцо', min: 90, max: 199, outer: 0.82, inner: 0.66, energy: 0.18 },
    { id: 'middle', label: 'Среднее кольцо', min: 200, max: 474, outer: 0.66, inner: 0.48, energy: 0.36 },
    { id: 'high', label: 'Высокое кольцо', min: 475, max: 699, outer: 0.48, inner: 0.32, energy: 0.58 },
    { id: 'inner', label: 'Внутреннее кольцо', min: 700, max: 899, outer: 0.32, inner: 0.16, energy: 0.80 },
    { id: 'crown', label: 'Коронное кольцо', min: 900, max: 999, outer: 0.16, inner: 0.00, energy: 1.00 }
  ];

  const BASE_ORGANS = {
    heart: { label: 'Сердце', vital: true, upkeep: 1.0 },
    lungs: { label: 'Дыхательная система', vital: true, upkeep: 0.8 },
    stomach: { label: 'Пищеварение', vital: true, upkeep: 0.7 },
    brain: { label: 'Нервный узел', vital: true, upkeep: 0.9 },
    legs: { label: 'Органы движения', vital: false, upkeep: 0.8 },
    claws: { label: 'Атакующие органы', vital: false, upkeep: 0.6 },
    senses: { label: 'Органы чувств', vital: false, upkeep: 0.5 }
  };

  const SPECIES = {
    leafhorn: {
      id: 'leafhorn',
      name: 'Листорог',
      color: '#7dcc67',
      diet: 'herbivore',
      social: 'herd',
      reproduction: 'sexual',
      adultAge: 240,
      oldAge: 2400,
      litter: [1, 2],
      moveSpeed: 18,
      sight: 115,
      aggression: 0.10,
      courage: 0.34,
      metabolism: 0.72,
      fertility: 0.82,
      foodEfficiency: 0.92,
      carcassEfficiency: 0.24,
      adaptationBias: { endurance: 0.42, agility: 0.28, strength: 0.18, intellect: 0.12 },
      supportWeights: { strength: 0.18, endurance: 0.38, agility: 0.28, intellect: 0.16 },
      statCost: { strength: 10, endurance: 9, agility: 10, intellect: 12 },
      bodyEfficiency: 1.0,
      initialPotential: { strength: 170, endurance: 280, agility: 210, intellect: 110 },
      initialLevelRange: [18, 38],
      organs: { ...BASE_ORGANS, horns: { label: 'Листовые рога', vital: false, upkeep: 0.4 } },
      actions: ['graze', 'flee', 'herd-call', 'horn-charge'],
      baseSkills: { foraging: 24, evasion: 18, coordination: 26, charge: 8 }
    },
    duskfang: {
      id: 'duskfang',
      name: 'Сумеречный гончий',
      color: '#9f6ad9',
      diet: 'carnivore',
      social: 'pack',
      reproduction: 'sexual',
      adultAge: 300,
      oldAge: 3000,
      litter: [2, 4],
      moveSpeed: 25,
      sight: 150,
      aggression: 0.72,
      courage: 0.60,
      metabolism: 1.05,
      fertility: 0.58,
      foodEfficiency: 0.72,
      carcassEfficiency: 0.62,
      adaptationBias: { strength: 0.30, endurance: 0.24, agility: 0.34, intellect: 0.12 },
      supportWeights: { strength: 0.30, endurance: 0.24, agility: 0.34, intellect: 0.12 },
      statCost: { strength: 9, endurance: 10, agility: 8, intellect: 13 },
      bodyEfficiency: 1.02,
      initialPotential: { strength: 330, endurance: 250, agility: 380, intellect: 130 },
      initialLevelRange: [42, 78],
      organs: { ...BASE_ORGANS, fangs: { label: 'Сумеречные клыки', vital: false, upkeep: 0.7 } },
      actions: ['stalk', 'pack-hunt', 'bite', 'retreat'],
      baseSkills: { tracking: 28, bite: 26, coordination: 34, evasion: 18 }
    },
    stoneback: {
      id: 'stoneback',
      name: 'Камнегрив',
      color: '#c38a54',
      diet: 'carnivore',
      social: 'solitary',
      reproduction: 'sexual',
      adultAge: 600,
      oldAge: 6200,
      litter: [1, 1],
      moveSpeed: 13,
      sight: 125,
      aggression: 0.58,
      courage: 0.82,
      metabolism: 0.82,
      fertility: 0.22,
      foodEfficiency: 0.76,
      carcassEfficiency: 0.56,
      adaptationBias: { strength: 0.39, endurance: 0.39, agility: 0.10, intellect: 0.12 },
      supportWeights: { strength: 0.38, endurance: 0.40, agility: 0.10, intellect: 0.12 },
      statCost: { strength: 8, endurance: 8, agility: 15, intellect: 13 },
      bodyEfficiency: 1.05,
      initialPotential: { strength: 900, endurance: 980, agility: 240, intellect: 270 },
      initialLevelRange: [115, 185],
      organs: { ...BASE_ORGANS, plates: { label: 'Каменные пластины', vital: false, upkeep: 1.0 } },
      actions: ['ambush', 'maul', 'guard-carcass', 'roar'],
      baseSkills: { maul: 44, resilience: 52, tracking: 20, intimidation: 28 }
    },
    bonebeak: {
      id: 'bonebeak',
      name: 'Костеклюв',
      color: '#d8d36a',
      diet: 'scavenger',
      social: 'flock',
      reproduction: 'eggs',
      adultAge: 180,
      oldAge: 1800,
      litter: [2, 5],
      moveSpeed: 22,
      sight: 180,
      aggression: 0.24,
      courage: 0.28,
      metabolism: 0.88,
      fertility: 0.68,
      foodEfficiency: 0.55,
      carcassEfficiency: 1.12,
      adaptationBias: { strength: 0.16, endurance: 0.24, agility: 0.33, intellect: 0.27 },
      supportWeights: { strength: 0.14, endurance: 0.24, agility: 0.34, intellect: 0.28 },
      statCost: { strength: 13, endurance: 10, agility: 9, intellect: 9 },
      bodyEfficiency: 0.98,
      initialPotential: { strength: 150, endurance: 220, agility: 340, intellect: 290 },
      initialLevelRange: [32, 68],
      organs: { ...BASE_ORGANS, beak: { label: 'Разделочный клюв', vital: false, upkeep: 0.45 }, wings: { label: 'Крылья', vital: false, upkeep: 0.9 } },
      actions: ['circle', 'scavenge', 'steal-piece', 'alarm-call'],
      baseSkills: { scavenging: 36, flight: 30, awareness: 32, evasion: 24 }
    },
    sandborer: {
      id: 'sandborer',
      name: 'Пескорой',
      color: '#6cc5c9',
      diet: 'omnivore',
      social: 'family',
      reproduction: 'budding',
      adultAge: 360,
      oldAge: 3800,
      litter: [1, 2],
      moveSpeed: 16,
      sight: 95,
      aggression: 0.32,
      courage: 0.48,
      metabolism: 0.64,
      fertility: 0.48,
      foodEfficiency: 0.80,
      carcassEfficiency: 0.64,
      adaptationBias: { strength: 0.22, endurance: 0.35, agility: 0.19, intellect: 0.24 },
      supportWeights: { strength: 0.22, endurance: 0.36, agility: 0.18, intellect: 0.24 },
      statCost: { strength: 10, endurance: 8, agility: 12, intellect: 10 },
      bodyEfficiency: 1.01,
      initialPotential: { strength: 260, endurance: 440, agility: 190, intellect: 300 },
      initialLevelRange: [48, 92],
      organs: { ...BASE_ORGANS, drill: { label: 'Роющий венец', vital: false, upkeep: 0.75 } },
      actions: ['burrow', 'forage-root', 'hide', 'tunnel-ambush'],
      baseSkills: { burrowing: 38, foraging: 24, ambush: 16, resilience: 30 }
    },
    lumenmold: {
      id: 'lumenmold',
      name: 'Светогриб',
      color: '#65e0b2',
      diet: 'photosynthetic',
      social: 'colony',
      reproduction: 'spores',
      adultAge: 480,
      oldAge: 7200,
      litter: [2, 8],
      moveSpeed: 4,
      sight: 80,
      aggression: 0.08,
      courage: 0.70,
      metabolism: 0.38,
      fertility: 0.74,
      foodEfficiency: 0.92,
      carcassEfficiency: 0.42,
      adaptationBias: { strength: 0.08, endurance: 0.31, agility: 0.06, intellect: 0.55 },
      supportWeights: { strength: 0.08, endurance: 0.30, agility: 0.06, intellect: 0.56 },
      statCost: { strength: 18, endurance: 9, agility: 20, intellect: 7 },
      bodyEfficiency: 1.03,
      initialPotential: { strength: 90, endurance: 430, agility: 60, intellect: 740 },
      initialLevelRange: [55, 120],
      organs: { ...BASE_ORGANS, core: { label: 'Световое ядро', vital: true, upkeep: 0.9 }, spores: { label: 'Споровые мешки', vital: false, upkeep: 0.5 } },
      actions: ['photosynthesize', 'root-network', 'spore-cloud', 'energy-pulse'],
      baseSkills: { energyControl: 42, awareness: 18, regeneration: 38, coordination: 28 }
    }
  };

  const MUTATIONS = [
    { id: 'denseMuscle', label: 'Плотные мышцы', stat: 'strength', amount: 24, cost: { agility: -5 }, organ: 'claws' },
    { id: 'deepLung', label: 'Глубокое дыхание', stat: 'endurance', amount: 22, cost: {}, organ: 'lungs' },
    { id: 'quickNerve', label: 'Быстрый нервный контур', stat: 'agility', amount: 20, cost: { endurance: -4 }, organ: 'brain' },
    { id: 'echoSense', label: 'Эхо-чувство', stat: 'intellect', amount: 18, cost: {}, organ: 'senses' },
    { id: 'efficientGut', label: 'Эффективное пищеварение', stat: 'endurance', amount: 12, cost: {}, organ: 'stomach', foodEfficiency: 0.08 },
    { id: 'soulEtching', label: 'Насечка души', stat: 'intellect', amount: 28, cost: { strength: -6 }, organ: 'brain', retention: 0.12 }
  ];

  return {
    VERSION: '0.4.0-alpha.1',
    WORLD: {
      width: 1600,
      height: 1600,
      initialPopulation: {
        leafhorn: 54,
        duskfang: 24,
        stoneback: 7,
        bonebeak: 28,
        sandborer: 20,
        lumenmold: 24
      },
      initialFoodNodes: 420,
      maxCreatures: 700,
      maxCarcasses: 500,
      tickSeconds: 1,
      actionInterval: 4,
      corpseFreshSeconds: 300,
      corpseSpoiledSeconds: 600,
      corpseGoneSeconds: 1200,
      baseLevelSeconds: 60,
      adaptationPotentialPerHour: [1, 3],
      soulDamage: [7, 11, 16, 24, 35, 53],
      rebirthMinSeconds: 20,
      rebirthMaxSeconds: 900
    },
    RINGS,
    SPECIES,
    MUTATIONS,
    STATS: ['strength', 'endurance', 'agility', 'intellect']
  };
});
